  # subnet for admiral cluster
	#
  # This file is generated by 'gen-vpc-subnet-modules-tf.sh'
  # The variable values for CIDR blocks and availability zones are generated dynamically
  # by the same script, according to the selected AWS region
	
		variable "admiral_subnet_a" { default = "10.0.20.0/24" }
		variable "admiral_subnet_az_a" { default = "ap-southeast-1a" }
		variable "admiral_subnet_b" { default = "10.0.21.0/24" }
		variable "admiral_subnet_az_b" { default = "ap-southeast-1b" }
	
		resource "aws_subnet" "admiral_a" {
				vpc_id = "${aws_vpc.cluster_vpc.id}"
				availability_zone = "${var.admiral_subnet_az_a}"
				cidr_block = "${var.admiral_subnet_a}"
				map_public_ip_on_launch = "true"
				tags {
						Name = "admiral_a"
				}
		}
		
		resource "aws_route_table_association" "admiral_rt_a" {
				subnet_id = "${aws_subnet.admiral_a.id}"
				route_table_id = "${aws_route_table.cluster_vpc.id}"
		}
		
		resource "aws_subnet" "admiral_b" {
				vpc_id = "${aws_vpc.cluster_vpc.id}"
				availability_zone = "${var.admiral_subnet_az_b}"
				cidr_block = "${var.admiral_subnet_b}"
				map_public_ip_on_launch = "true"
				tags {
						Name = "admiral_b"
				}
		}
		
		resource "aws_route_table_association" "admiral_rt_b" {
				subnet_id = "${aws_subnet.admiral_b.id}"
				route_table_id = "${aws_route_table.cluster_vpc.id}"
		}
		
	
		output "admiral_subnet_a_id" {value = "${aws_subnet.admiral_a.id}"}
		output "admiral_subnet_az_a" {value = "${var.admiral_subnet_az_a}"}
		output "admiral_subnet_b_id" {value = "${aws_subnet.admiral_b.id}"}
		output "admiral_subnet_az_b" {value = "${var.admiral_subnet_az_b}"}
