  # subnet for elb cluster
	#
  # This file is generated by 'gen-vpc-subnet-modules-tf.sh'
  # The variable values for CIDR blocks and availability zones are generated dynamically
  # by the same script, according to the selected AWS region
	
		variable "elb_subnet_a" { default = "10.0.40.0/24" }
		variable "elb_subnet_az_a" { default = "ap-southeast-1a" }
		variable "elb_subnet_b" { default = "10.0.41.0/24" }
		variable "elb_subnet_az_b" { default = "ap-southeast-1b" }
	
		resource "aws_subnet" "elb_a" {
				vpc_id = "${aws_vpc.cluster_vpc.id}"
				availability_zone = "${var.elb_subnet_az_a}"
				cidr_block = "${var.elb_subnet_a}"
				map_public_ip_on_launch = "true"
				tags {
						Name = "elb_a"
				}
		}
		
		resource "aws_route_table_association" "elb_rt_a" {
				subnet_id = "${aws_subnet.elb_a.id}"
				route_table_id = "${aws_route_table.cluster_vpc.id}"
		}
		
		resource "aws_subnet" "elb_b" {
				vpc_id = "${aws_vpc.cluster_vpc.id}"
				availability_zone = "${var.elb_subnet_az_b}"
				cidr_block = "${var.elb_subnet_b}"
				map_public_ip_on_launch = "true"
				tags {
						Name = "elb_b"
				}
		}
		
		resource "aws_route_table_association" "elb_rt_b" {
				subnet_id = "${aws_subnet.elb_b.id}"
				route_table_id = "${aws_route_table.cluster_vpc.id}"
		}
		
	
		output "elb_subnet_a_id" {value = "${aws_subnet.elb_a.id}"}
		output "elb_subnet_az_a" {value = "${var.elb_subnet_az_a}"}
		output "elb_subnet_b_id" {value = "${aws_subnet.elb_b.id}"}
		output "elb_subnet_az_b" {value = "${var.elb_subnet_az_b}"}
