  # subnet for etcd cluster
	#
  # This file is generated by 'gen-vpc-subnet-modules-tf.sh'
  # The variable values for CIDR blocks and availability zones are generated dynamically
  # by the same script, according to the selected AWS region
	
		variable "etcd_subnet_b" { default = "10.0.10.0/24" }
		variable "etcd_subnet_az_b" { default = "us-east-1b" }
		variable "etcd_subnet_c" { default = "10.0.11.0/24" }
		variable "etcd_subnet_az_c" { default = "us-east-1c" }
		variable "etcd_subnet_d" { default = "10.0.12.0/24" }
		variable "etcd_subnet_az_d" { default = "us-east-1d" }
		variable "etcd_subnet_e" { default = "10.0.13.0/24" }
		variable "etcd_subnet_az_e" { default = "us-east-1e" }
	
		resource "aws_subnet" "etcd_b" {
				vpc_id = "${aws_vpc.cluster_vpc.id}"
				availability_zone = "${var.etcd_subnet_az_b}"
				cidr_block = "${var.etcd_subnet_b}"
				map_public_ip_on_launch = "true"
				tags {
						Name = "etcd_b"
				}
		}
		
		resource "aws_route_table_association" "etcd_rt_b" {
				subnet_id = "${aws_subnet.etcd_b.id}"
				route_table_id = "${aws_route_table.cluster_vpc.id}"
		}
		
		resource "aws_subnet" "etcd_c" {
				vpc_id = "${aws_vpc.cluster_vpc.id}"
				availability_zone = "${var.etcd_subnet_az_c}"
				cidr_block = "${var.etcd_subnet_c}"
				map_public_ip_on_launch = "true"
				tags {
						Name = "etcd_c"
				}
		}
		
		resource "aws_route_table_association" "etcd_rt_c" {
				subnet_id = "${aws_subnet.etcd_c.id}"
				route_table_id = "${aws_route_table.cluster_vpc.id}"
		}
		
		resource "aws_subnet" "etcd_d" {
				vpc_id = "${aws_vpc.cluster_vpc.id}"
				availability_zone = "${var.etcd_subnet_az_d}"
				cidr_block = "${var.etcd_subnet_d}"
				map_public_ip_on_launch = "true"
				tags {
						Name = "etcd_d"
				}
		}
		
		resource "aws_route_table_association" "etcd_rt_d" {
				subnet_id = "${aws_subnet.etcd_d.id}"
				route_table_id = "${aws_route_table.cluster_vpc.id}"
		}
		
		resource "aws_subnet" "etcd_e" {
				vpc_id = "${aws_vpc.cluster_vpc.id}"
				availability_zone = "${var.etcd_subnet_az_e}"
				cidr_block = "${var.etcd_subnet_e}"
				map_public_ip_on_launch = "true"
				tags {
						Name = "etcd_e"
				}
		}
		
		resource "aws_route_table_association" "etcd_rt_e" {
				subnet_id = "${aws_subnet.etcd_e.id}"
				route_table_id = "${aws_route_table.cluster_vpc.id}"
		}
		
	
		output "etcd_subnet_b_id" {value = "${aws_subnet.etcd_b.id}"}
		output "etcd_subnet_az_b" {value = "${var.etcd_subnet_az_b}"}
		output "etcd_subnet_c_id" {value = "${aws_subnet.etcd_c.id}"}
		output "etcd_subnet_az_c" {value = "${var.etcd_subnet_az_c}"}
		output "etcd_subnet_d_id" {value = "${aws_subnet.etcd_d.id}"}
		output "etcd_subnet_az_d" {value = "${var.etcd_subnet_az_d}"}
		output "etcd_subnet_e_id" {value = "${aws_subnet.etcd_e.id}"}
		output "etcd_subnet_az_e" {value = "${var.etcd_subnet_az_e}"}
