  # subnet for etcd cluster
	#
  # This file is generated by 'gen-vpc-subnet-modules-tf.sh'
  # The variable values for CIDR blocks and availability zones are generated dynamically
  # by the same script, according to the selected AWS region
	
		variable "etcd_subnet_a" { default = "10.0.10.0/24" }
		variable "etcd_subnet_az_a" { default = "ap-southeast-1a" }
		variable "etcd_subnet_b" { default = "10.0.11.0/24" }
		variable "etcd_subnet_az_b" { default = "ap-southeast-1b" }
	
		resource "aws_subnet" "etcd_a" {
				vpc_id = "${aws_vpc.cluster_vpc.id}"
				availability_zone = "${var.etcd_subnet_az_a}"
				cidr_block = "${var.etcd_subnet_a}"
				map_public_ip_on_launch = "true"
				tags {
						Name = "etcd_a"
				}
		}
		
		resource "aws_route_table_association" "etcd_rt_a" {
				subnet_id = "${aws_subnet.etcd_a.id}"
				route_table_id = "${aws_route_table.cluster_vpc.id}"
		}
		
		resource "aws_subnet" "etcd_b" {
				vpc_id = "${aws_vpc.cluster_vpc.id}"
				availability_zone = "${var.etcd_subnet_az_b}"
				cidr_block = "${var.etcd_subnet_b}"
				map_public_ip_on_launch = "true"
				tags {
						Name = "etcd_b"
				}
		}
		
		resource "aws_route_table_association" "etcd_rt_b" {
				subnet_id = "${aws_subnet.etcd_b.id}"
				route_table_id = "${aws_route_table.cluster_vpc.id}"
		}
		
	
		output "etcd_subnet_a_id" {value = "${aws_subnet.etcd_a.id}"}
		output "etcd_subnet_az_a" {value = "${var.etcd_subnet_az_a}"}
		output "etcd_subnet_b_id" {value = "${aws_subnet.etcd_b.id}"}
		output "etcd_subnet_az_b" {value = "${var.etcd_subnet_az_b}"}
