  # subnet for rds cluster
	#
  # This file is generated by 'gen-vpc-subnet-modules-tf.sh'
  # The variable values for CIDR blocks and availability zones are generated dynamically
  # by the same script, according to the selected AWS region
	
		variable "rds_subnet_a" { default = "10.0.50.0/24" }
		variable "rds_subnet_az_a" { default = "ap-southeast-1a" }
		variable "rds_subnet_b" { default = "10.0.51.0/24" }
		variable "rds_subnet_az_b" { default = "ap-southeast-1b" }
	
		resource "aws_subnet" "rds_a" {
				vpc_id = "${aws_vpc.cluster_vpc.id}"
				availability_zone = "${var.rds_subnet_az_a}"
				cidr_block = "${var.rds_subnet_a}"
				map_public_ip_on_launch = "true"
				tags {
						Name = "rds_a"
				}
		}
		
		resource "aws_route_table_association" "rds_rt_a" {
				subnet_id = "${aws_subnet.rds_a.id}"
				route_table_id = "${aws_route_table.cluster_vpc.id}"
		}
		
		resource "aws_subnet" "rds_b" {
				vpc_id = "${aws_vpc.cluster_vpc.id}"
				availability_zone = "${var.rds_subnet_az_b}"
				cidr_block = "${var.rds_subnet_b}"
				map_public_ip_on_launch = "true"
				tags {
						Name = "rds_b"
				}
		}
		
		resource "aws_route_table_association" "rds_rt_b" {
				subnet_id = "${aws_subnet.rds_b.id}"
				route_table_id = "${aws_route_table.cluster_vpc.id}"
		}
		
	
		output "rds_subnet_a_id" {value = "${aws_subnet.rds_a.id}"}
		output "rds_subnet_az_a" {value = "${var.rds_subnet_az_a}"}
		output "rds_subnet_b_id" {value = "${aws_subnet.rds_b.id}"}
		output "rds_subnet_az_b" {value = "${var.rds_subnet_az_b}"}
