  # subnet for worker cluster
	#
  # This file is generated by 'gen-vpc-subnet-modules-tf.sh'
  # The variable values for CIDR blocks and availability zones are generated dynamically
  # by the same script, according to the selected AWS region
	
		variable "worker_subnet_b" { default = "10.0.30.0/24" }
		variable "worker_subnet_az_b" { default = "us-east-1b" }
		variable "worker_subnet_c" { default = "10.0.31.0/24" }
		variable "worker_subnet_az_c" { default = "us-east-1c" }
		variable "worker_subnet_d" { default = "10.0.32.0/24" }
		variable "worker_subnet_az_d" { default = "us-east-1d" }
		variable "worker_subnet_e" { default = "10.0.33.0/24" }
		variable "worker_subnet_az_e" { default = "us-east-1e" }
	
		resource "aws_subnet" "worker_b" {
				vpc_id = "${aws_vpc.cluster_vpc.id}"
				availability_zone = "${var.worker_subnet_az_b}"
				cidr_block = "${var.worker_subnet_b}"
				map_public_ip_on_launch = "true"
				tags {
						Name = "worker_b"
				}
		}
		
		resource "aws_route_table_association" "worker_rt_b" {
				subnet_id = "${aws_subnet.worker_b.id}"
				route_table_id = "${aws_route_table.cluster_vpc.id}"
		}
		
		resource "aws_subnet" "worker_c" {
				vpc_id = "${aws_vpc.cluster_vpc.id}"
				availability_zone = "${var.worker_subnet_az_c}"
				cidr_block = "${var.worker_subnet_c}"
				map_public_ip_on_launch = "true"
				tags {
						Name = "worker_c"
				}
		}
		
		resource "aws_route_table_association" "worker_rt_c" {
				subnet_id = "${aws_subnet.worker_c.id}"
				route_table_id = "${aws_route_table.cluster_vpc.id}"
		}
		
		resource "aws_subnet" "worker_d" {
				vpc_id = "${aws_vpc.cluster_vpc.id}"
				availability_zone = "${var.worker_subnet_az_d}"
				cidr_block = "${var.worker_subnet_d}"
				map_public_ip_on_launch = "true"
				tags {
						Name = "worker_d"
				}
		}
		
		resource "aws_route_table_association" "worker_rt_d" {
				subnet_id = "${aws_subnet.worker_d.id}"
				route_table_id = "${aws_route_table.cluster_vpc.id}"
		}
		
		resource "aws_subnet" "worker_e" {
				vpc_id = "${aws_vpc.cluster_vpc.id}"
				availability_zone = "${var.worker_subnet_az_e}"
				cidr_block = "${var.worker_subnet_e}"
				map_public_ip_on_launch = "true"
				tags {
						Name = "worker_e"
				}
		}
		
		resource "aws_route_table_association" "worker_rt_e" {
				subnet_id = "${aws_subnet.worker_e.id}"
				route_table_id = "${aws_route_table.cluster_vpc.id}"
		}
		
	
		output "worker_subnet_b_id" {value = "${aws_subnet.worker_b.id}"}
		output "worker_subnet_az_b" {value = "${var.worker_subnet_az_b}"}
		output "worker_subnet_c_id" {value = "${aws_subnet.worker_c.id}"}
		output "worker_subnet_az_c" {value = "${var.worker_subnet_az_c}"}
		output "worker_subnet_d_id" {value = "${aws_subnet.worker_d.id}"}
		output "worker_subnet_az_d" {value = "${var.worker_subnet_az_d}"}
		output "worker_subnet_e_id" {value = "${aws_subnet.worker_e.id}"}
		output "worker_subnet_az_e" {value = "${var.worker_subnet_az_e}"}
