  # subnet for worker cluster
	#
  # This file is generated by 'gen-vpc-subnet-modules-tf.sh'
  # The variable values for CIDR blocks and availability zones are generated dynamically
  # by the same script, according to the selected AWS region
	
		variable "worker_subnet_a" { default = "10.0.30.0/24" }
		variable "worker_subnet_az_a" { default = "ap-southeast-1a" }
		variable "worker_subnet_b" { default = "10.0.31.0/24" }
		variable "worker_subnet_az_b" { default = "ap-southeast-1b" }
	
		resource "aws_subnet" "worker_a" {
				vpc_id = "${aws_vpc.cluster_vpc.id}"
				availability_zone = "${var.worker_subnet_az_a}"
				cidr_block = "${var.worker_subnet_a}"
				map_public_ip_on_launch = "true"
				tags {
						Name = "worker_a"
				}
		}
		
		resource "aws_route_table_association" "worker_rt_a" {
				subnet_id = "${aws_subnet.worker_a.id}"
				route_table_id = "${aws_route_table.cluster_vpc.id}"
		}
		
		resource "aws_subnet" "worker_b" {
				vpc_id = "${aws_vpc.cluster_vpc.id}"
				availability_zone = "${var.worker_subnet_az_b}"
				cidr_block = "${var.worker_subnet_b}"
				map_public_ip_on_launch = "true"
				tags {
						Name = "worker_b"
				}
		}
		
		resource "aws_route_table_association" "worker_rt_b" {
				subnet_id = "${aws_subnet.worker_b.id}"
				route_table_id = "${aws_route_table.cluster_vpc.id}"
		}
		
	
		output "worker_subnet_a_id" {value = "${aws_subnet.worker_a.id}"}
		output "worker_subnet_az_a" {value = "${var.worker_subnet_az_a}"}
		output "worker_subnet_b_id" {value = "${aws_subnet.worker_b.id}"}
		output "worker_subnet_az_b" {value = "${var.worker_subnet_az_b}"}
