variable "aws_account_id" { }
variable "aws_account_region" { }
variable "aws_account_user" { }
variable "deployment_user" { default = "deployment" }

resource "aws_iam_user" "deployment" {
    name = "${var.deployment_user}"
    path = "/system/"
}
resource "aws_iam_user_policy" "deployment" {
    name = "deployment"
    user = "${aws_iam_user.deployment.name}"
    policy = "${file(\"${path.module}/deployment_policy.json\")}"
}
resource "aws_iam_access_key" "deployment" {
    user = "${aws_iam_user.deployment.name}"

    provisioner "local-exec" {
    command = <<CMD_DATA
cat > cloud-config/aws-file.yaml <<EOF 
  # Generated by iam.tf
  - path: /etc/aws/account.envvars
    content: |
        AWS_ACCOUNT=${var.aws_account_id}
        AWS_USER=${var.aws_account_user}
        AWS_DEFAULT_REGION=${var.aws_account_region}
  - path: /root/.aws/envvars
    content: |
        AWS_ACCOUNT=${var.aws_account_id}
        AWS_USER=${aws_iam_user.deployment.name}
        AWS_ACCESS_KEY_ID="${aws_iam_access_key.deployment.id}"
        AWS_SECRET_ACCESS_KEY=${aws_iam_access_key.deployment.secret}
        AWS_DEFAULT_REGION=${var.aws_account_region}
  - path: /root/.aws/config
    content: |
        [default]
        aws_access_key_id="${aws_iam_access_key.deployment.id}"
        aws_secret_access_key=${aws_iam_access_key.deployment.secret}
        region=${var.aws_account_region}
  - path: /home/core/.aws/envvars
    content: |
        AWS_ACCOUNT=${var.aws_account_id}
        AWS_USER=${aws_iam_user.deployment.name}
        AWS_ACCESS_KEY_ID="${aws_iam_access_key.deployment.id}"
        AWS_SECRET_ACCESS_KEY=${aws_iam_access_key.deployment.secret}
        AWS_DEFAULT_REGION=${var.aws_account_region}
  - path: /home/core/.aws/config
    content: |
        [default]
        aws_access_key_id="${aws_iam_access_key.deployment.id}"
        aws_secret_access_key=${aws_iam_access_key.deployment.secret}
        region=${var.aws_account_region}
CMD_DATA
    }
}
