alias tf='terraform'
alias tfp='tf plan --var-file=../tfcommon/keys.tfvars --var-file=../tfcommon/network.tfvars'
alias tfr='~/bin/terraform/terraform --var-file=../tfcommon/keys.tfvars --var-file=network.tfvars refresh '
alias tfdp='tf  plan -destroy --var-file=../tfcommon/keys.tfvars  --var-file=../tfcommon/network.tfvars --out=destroy.tfplan'
alias tfa='tf apply --var-file=../tfcommon/keys.tfvars --var-file=../tfcommon/network.tfvars'
alias tfda='tf apply destroy.tfplan '
alias tfg='tf graph'
alias tfs='tf show terraform.tfstate'
