#!/bin/bash
echo "# Generated by make vpc/gen_vpc_vars"
echo "# $(date)"
echo "$(terraform output)" | while read line
do
	IFS=' = ' read -r -a array <<< "$line"
	if [ ! -z "${array[0]}" ];
	then
		echo variable \"${array[0]}\" { default = \"${array[1]}\"}
	fi
done