#!/bin/bash

TFCOMMON="../tfcommon"

RESOURCES="
security_group_admiral
security_group_dockerhub
security_group_elb
security_group_etcd
security_group_worker
security_group_rds
subnet_etcd-us-west-2a
subnet_etcd-us-west-2b
subnet_etcd-us-west-2c
subnet_elb-us-west-2a
subnet_elb-us-west-2b
subnet_elb-us-west-2c
subnet_rds-us-west-2a
subnet_rds-us-west-2b
subnet_rds-us-west-2c
subnet_admiral-us-west-2a
subnet_admiral-us-west-2b
subnet_admiral-us-west-2c
subnet_worker-us-west-2a
subnet_worker-us-west-2b
subnet_worker-us-west-2c
vpc_cidr
vpc_id"

NETWORKTF="${TFCOMMON}/network.tf"
NETWORKTFVARS="${TFCOMMON}/network.tfvars"
rm -f ${NETWORKTF} ${NETWORKTFVARS}
echo "# Auto-generated by $0." > ${NETWORKTF}
echo "# Auto-generated by $0." > ${NETWORKTFVARS}
for i in $RESOURCES
do
  echo $i
  echo variable \"$i\" {} >> ${NETWORKTF}
  echo -n "$i=" >> ${NETWORKTFVARS}
  terraform output $i >> ${NETWORKTFVARS}
done
