#!/bin/bash
echo "# Generated by make vpc/gen_vpc_vars"
echo "# $(date)"
echo "$(terraform output)" | while read line
do
	IFS=' = ' read -r -a array <<< "$line"
	echo variable \"${array[0]}\" { default = \"${array[1]}\"}
done